
-- create
CREATE TABLE STUDENT (
  stId INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

-- insert
INSERT INTO STUDENT VALUES (0001, 'Clark');
INSERT INTO STUDENT VALUES (0002, 'Dave');
INSERT INTO STUDENT VALUES (0003, 'Ava');

-- fetch 
SELECT * FROM STUDENT WHERE name = 'Clark';

-- STUDENTS SCORES
-- create
CREATE TABLE STUDENT_SCORE (
  stScoreId INTEGER PRIMARY KEY,
  stId INTEGER,
  CONSTRAINT fk_stId 
    FOREIGN KEY (stId)
    REFERENCES STUDENT (stId),
  score INTEGER NOT NULL
);

-- insert
INSERT INTO STUDENT_SCORE VALUES (0001, 0001, 10);
INSERT INTO STUDENT_SCORE VALUES (0002, 0001, 1);
INSERT INTO STUDENT_SCORE VALUES (0003, 0002, 5);
INSERT INTO STUDENT_SCORE VALUES (0004, 0002, 5);
INSERT INTO STUDENT_SCORE VALUES (0005, 0003, 10);
INSERT INTO STUDENT_SCORE VALUES (0006, 0003, 3);

-- fetch 
SELECT * FROM STUDENT_SCORE WHERE stId = 0001;


-- Get AVG Score Group By Student Name

SELECT st.name, AVG(stS.Score) FROM STUDENT st 
INNER JOIN  STUDENT_SCORE stS
ON st.stId = stS.stId
GROUP BY st.name
ORDER BY st.name ASC